### ISSUE TITLE
Input Accepts invalid Strings

### ISSUE THREAD

**Issue by KingBael09** [Umesh2202/TODO-app#2]
### Input validation is required as it takes empty strings 

![Bug](https://user-images.githubusercontent.com/84223691/216773360-03777b78-7dd9-4b2c-ac11-c8d1b35a8c64.png)

**Comment by Umesh2202** [comment]
You need to add firebase credentials for the app to work properly.

**Comment by KingBael09** [comment]
Seems to be a frontend input validation problem.

Having some sort of input validation can save unnecessary api calls.

**Comment by Umesh2202** [comment]
Fixed
